# Auto-generated NCERT Book Mapping

NCERT_BOOK_MAPPING = {
    "1_Mathematics": "aejm1",
    "1_Hindi": "ahsr1",
    "1_English": "aemr1",
    "1_Urdu": "aush1",
    "2_Mathematics": "bejm1",
    "2_Hindi": "bhsr1",
    "2_English": "bemr1",
    "2_Urdu": "bush1",
    "3_Hindi": "chve1",
    "3_Environmental Studies": "ceap1",
    "3_English": "cesa1",
    "3_Mathematics": "cemm1",
    "3_Urdu": "cust1",
    "3_The World Around Us": "ceev1",
    "3_Arts": "cebu1",
    "3_Physical Education and Well Being": "ceky1",
    "4_Mathematics": "demm1",
    "4_Hindi": "dhve1",
    "4_Environmental Studies": "deap1",
    "4_The World Around Us": "deev1",
    "4_English": "desa1",
    "4_Arts": "debu1",
    "4_Physical Education and Well Being": "deky1",
    "4_Urdu": "dust1",
    "5_Mathematics": "eemh1",
    "5_Hindi": "ehhn1",
    "5_English": "eeen1",
    "5_The World Around Us": "eeev1",
    "5_Arts": "eebu1",
    "5_Physical Education and Well Being": "eeky1",
    "5_Urdu": "eulb1",
    "5_Environmental Studies": "ehap1",
    "6_Hindi": "fhml1",
    "6_Vocational Education": "fekb1",
    "6_Physical Education and Well Being": "feky1",
    "6_English": "fepr1",
    "6_Mathematics": "fegp1",
    "6_Social Science": "fees1",
    "6_Sanskrit": "fsde1",
    "6_Science": "fecu1",
    "6_Arts": "fekr1",
    "6_Urdu": "fuky1",
    "7_Mathematics": "gegp1",
    "7_Arts": "gekr1",
    "7_Hindi": "ghml1",
    "7_Sanskrit": "gsde1",
    "7_Science": "gecu1",
    "7_English": "gepr1",
    "7_Social Science": "gees1",
    "7_Physical Education and Well Being": "geky1",
    "7_Vocational Education": "gekb1",
    "7_Urdu": "guky1",
    "8_Mathematics": "hemh1",
    "8_Arts": "hekr1",
    "8_Hindi": "hhvs1",
    "8_Sanskrit": "hhsk1",
    "8_Science": "hesc1",
    "8_English": "hehd1",
    "8_Social Science": "hess4",
    "8_Physical Education and Well Being": "heky1",
    "8_Vocational Education": "hekb1",
    "8_Urdu": "huaz1",
    "8_Class 8": "class4",
    "9_English": "iebe1",
    "9_Hindi": "ihga1",
    "9_Sanskrit": "ihsh1",
    "9_Mathematics": "iemh1",
    "9_Science": "iesc1",
    "9_Urdu": "iuju1",
    "9_Environmental Education": "iepb1",
    "9_Physical Education and Well Being": "iehp1",
    "9_Skill Education": "iekv1",
    "9_Vocational": "ievc1",
    "9_Arts": "iemr1",
    "10_Mathematics": "jemh1",
    "10_Science": "jesc1",
    "10_Hindi": "jhks1",
    "10_English": "jeff1",
    "10_Social Science": "jess1",
    "10_Sanskrit": "jhsk1",
    "10_Urdu": "jujp1",
    "10_Health and Physical Education": "jehp1",
    "11_Sanskrit": "khsk1",
    "11_Accountancy": "keac1",
    "11_Business Studies": "kebs1",
    "11_Chemistry": "kech1",
    "11_Mathematics": "kemh1",
    "11_Vocational": "kepc1",
    "11_Biology": "kebo1",
    "11_Home Science": "kehe1",
    "11_Psychology": "kepy1",
    "11_Economics": "keec1",
    "11_Geography": "kegy2",
    "11_Physics": "keph1",
    "11_Hindi": "khat1",
    "11_Sociology": "kesy1",
    "11_English": "keww1",
    "11_Political Science": "keps1",
    "11_History": "kehs1",
    "11_Heritage Crafts": "kehc1",
    "11_Graphics design": "kegd1",
    "11_Computers and Communication Technology": "kect1",
    "11_Fine Art": "kefa1",
    "11_Urdu": "kuna1",
    "11_Creative Writing and Translation": "khsr1",
    "11_Informatics Practices": "keip1",
    "11_Biotechnology": "kebt1",
    "11_Computer Science": "kecs1",
    "11_Health and Physical Education": "kehp1",
    "11_Knowledge Traditions Practices of India": "keks1",
    "11_Sangeet": "khtp1",
    "12_Accountancy": "leac1",
    "12_Mathematics": "lemh1",
    "12_Physics": "leph1",
    "12_Hindi": "lhat1",
    "12_English": "lekl1",
    "12_Biotechnology": "lebt1",
    "12_Biology": "lebo1",
    "12_History": "lehs1",
    "12_Geography": "legy1",
    "12_Psychology": "lepy1",
    "12_Sociology": "lesy1",
    "12_Chemistry": "lech1",
    "12_Sanskrit": "lhsk1",
    "12_Political Science": "leps1",
    "12_Home Science": "lehe1",
    "12_Economics": "leec2",
    "12_Business Studies": "lebs1",
    "12_Urdu": "luga1",
    "12_Heritage Crafts": "luhc1",
    "12_New Age Graphics Design": "legd1",
    "12_Creative Writing & Translation": "lucw1",
    "12_Fine Art": "lefa1",
    "12_Computer Science": "lecs1",
    "12_Informatics Practices": "leip1",
    "12_Sangeet": "lstp1",
    "13_Hindi": "kham1",
    "13_Sanskrit": "klss1",
    "13_Heritage Crafts": "mehc1",
    "13_Urdu": "kuza1",
    "14_Vocational": "geof1"
}

def get_ncert_book_code(class_grade: str, subject_name: str) -> str:
    # Remove "Grade " prefix if present in class_grade
    grade_num = class_grade.lower().replace("grade", "").strip()
    key = f"{grade_num}_{subject_name}"
    return NCERT_BOOK_MAPPING.get(key)
