"""baseline_schema

Revision ID: f665b2a95d6f
Revises: None
Create Date: 2026-08-18 00:35:17.926382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f665b2a95d6f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'admin'::character varying"))
    op.create_foreign_key(None, 'admins', 'schools', ['tenant_id'], ['tenant_id'], ondelete='SET NULL')
    op.drop_column('assessments', 'type')
    op.create_index(op.f('ix_chapters_tenant_id'), 'chapters', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'chapters', 'book_chapters', ['book_chapter_id'], ['id'], ondelete='SET NULL')
    op.alter_column('interview_messages', 'student_response',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('interview_messages', 'buddy_response',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('interviews', 'current_question_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('interviews', 'session_state',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'meet_buddy'::character varying"))
    op.alter_column('interviews', 'comfort_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('interviews', 'network_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'online'::character varying"))
    op.alter_column('interviews', 'completion_status',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'In Progress'::character varying"))
    op.alter_column('interviews', 'requires_review',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('interviews', 'raw_transcript',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('interviews', 'clean_transcript',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('interviews', 'validated_transcript',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('questions', 'maximum_followups',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('questions', 'minimum_coverage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0.6'))
    op.alter_column('questions', 'ideal_answer_length',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('50'))
    op.alter_column('questions', 'estimated_duration',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('120'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'estimated_duration',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('120'))
    op.alter_column('questions', 'ideal_answer_length',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('50'))
    op.alter_column('questions', 'minimum_coverage',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0.6'))
    op.alter_column('questions', 'maximum_followups',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('interviews', 'validated_transcript',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('interviews', 'clean_transcript',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('interviews', 'raw_transcript',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('interviews', 'requires_review',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('interviews', 'completion_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'In Progress'::character varying"))
    op.alter_column('interviews', 'network_status',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'online'::character varying"))
    op.alter_column('interviews', 'comfort_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('interviews', 'session_state',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'meet_buddy'::character varying"))
    op.alter_column('interviews', 'current_question_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('interview_messages', 'buddy_response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('interview_messages', 'student_response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_constraint(None, 'chapters', type_='foreignkey')
    op.drop_index(op.f('ix_chapters_tenant_id'), table_name='chapters')
    op.add_column('assessments', sa.Column('type', sa.VARCHAR(), server_default=sa.text("'Assessment'::character varying"), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admins', type_='foreignkey')
    op.alter_column('admins', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'admin'::character varying"))
    # ### end Alembic commands ###
